### ISSUE TITLE
On Gnome3, button text is clipped

### ISSUE THREAD

**Issue by pcav** [petercopdi/photo_to_kmz#4]
"Select folder". See attached image.
![dialog](https://cloud.githubusercontent.com/assets/691842/8544612/f87b7a32-24a6-11e5-9abe-dc8d97164ae4.png)

**Comment by petercopdi** [comment]
thanks.  I have to fix it.and upload to new plugin.please approve for download plugin

**Comment by pcav** [comment]
Thanks - looking forward for the new version. Just let me know, and I'll check it and approve it.
